NODE_ENV: test
client:
    urls: http://localhost:5173,http://localhost:4173,http://localhost:3000,
server:
    port: 8085
    host: localhost

database:
    url: mongodb://root:root@localhost:27017/order?authSource=admin
    name: order
    user: root
    password: root
auth:
    jwksUri: http://localhost:8081/.well-known/jwks.json
